//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.11 at 10:04:04 am IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com.SOAPwebService.SOAPdemo.allapis", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package allapis.soapdemo.soapwebservice.com;
